[package]
name = "keystore"
version = "0.1.0"
authors = ["Lars Kristjansen"]
edition = "2018"

[dependencies]
rsa = "0.3.0"
rand = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
