[package]
name = "cks"
version = "0.1.0"
authors = ["Lars Kristjansen"]
edition = "2018"

[dependencies]
keystore = { path = "../keystore", version = "0.1.0" }
structopt = "0.3"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"